#!/bin/bash
set -e

DOT_DIRECTORY="${HOME}/dotfiles"
DOT_TARBALL="https://github.com/akinobu-tani/dotfiles/tarball/master"
REMOTE_URL="git@github.com:akinobu-tani/dotfiles.git"

has() {
  type "$1" > /dev/null 2>&1
}

usage() {
  name=`basename $0`
  cat <<EOF
Usage:
  $name [arguments] [command]
Commands:
  init
Arguments:
  -f $(tput setaf 1)** warning **$(tput sgr0) Overwrite dotfiles.
  -h Print help (this message)
EOF
  exit 1
}

checkOS() {
  if [ "$(uname)" == 'Darwin' ]; then
    OS='Mac'
  elif [ "$(expr substr $(uname -s) 1 5)" == 'Linux' ]; then
    OS='Linux'
  elif [ "$(expr substr $(uname -s) 1 10)" == 'MINGW32_NT' ]; then
    OS='Cygwin'
  else
    echo "Your platform ($(uname -a)) is not supported."
    exit 1
  fi
}

while getopts :f:h opt; do
  case ${opt} in
    f)
      OVERWRITE=true
      ;;
    h)
      usage
      ;;
  esac
done
shift $((OPTIND - 1))

if [ -n "${OVERWRITE}" -o ! -d ${DOT_DIRECTORY} ]; then
  echo "Downloading dotfiles..."
  rm -rf ${DOT_DIRECTORY}
  mkdir ${DOT_DIRECTORY}

  if has "git"; then
    git clone --recursive "${REMOTE_URL}" "${DOT_DIRECTORY}"
  else
    curl -fsSLo ${HOME}/dotfiles.tar.gz ${DOT_TARBALL}
    tar -zxf ${HOME}/dotfiles.tar.gz --strip-components 1 -C ${DOT_DIRECTORY}
    rm -f ${HOME}/dotfiles.tar.gz
  fi

  echo "$(tput setaf 2)Download dotfiles complete!.$(tput sgr0)"
fi

FILES_TO_SYMLINK=(

  '.bash_profile'
  '.bashrc'
  '.gitconfig'
  'etc'

)

link_files() {
  cd ${DOT_DIRECTORY}
  for f in ${FILES_TO_SYMLINK[@]}; do
    ln -snfv ${DOT_DIRECTORY}/${f} ${HOME}/${f}
  done

  if [ "${OS}" == 'Mac' ]; then
    rm -rf "${HOME}/Library/Application Support/Sublime Text 3/Packages/User"
    ln -snfv "${DOT_DIRECTORY}/etc/sublime/mac/User" "${HOME}/Library/Application Support/Sublime Text 3/Packages/User"
  fi

  echo "$(tput setaf 2)Deploy dotfiles complete!.$(tput sgr0)"
}

FILES_TO_SYMLINK=(

  '.bash_profile'
  '.bashrc'
  '.gitconfig'
  'etc'

)

FILES_TO_SYMLINK_MAC=(

  '.gitconfig'

)

link_files() {
  cd ${DOT_DIRECTORY}
  for f in ${FILES_TO_SYMLINK[@]}; do
    ln -snfv ${DOT_DIRECTORY}/${f} ${HOME}/${f}
  done

  if [ "${OS}" == 'Mac' ]; then
    for f in ${FILES_TO_SYMLINK_MAC[@]}; do
      ln -snfv ${DOT_DIRECTORY}/mac/${f} ${HOME}/${f}
    done

    rm -rf "${HOME}/Library/Application Support/Sublime Text 3/Packages/User"
    ln -snfv "${DOT_DIRECTORY}/etc/sublime/mac/User" "${HOME}/Library/Application Support/Sublime Text 3/Packages/User"
  fi

  echo "$(tput setaf 2)Deploy dotfiles complete!.$(tput sgr0)"
}

# initialize() {
#   bash $(DOT_DIRECTORY)/init/init.sh
# }

checkOS
link_files

command=$1
[ $# -gt 0 ] && shift

case $command in
  init*)
    # initialize
    ;;
  *)
    ;;
esac

exit 0
