#!/bin/bash
set -e

DOT_DIRECTORY="${HOME}/dotfiles"
DOT_TARBALL="https://github.com/akinobu-tani/dotfiles/tarball/master"
REMOTE_URL="git@github.com:akinobu-tani/dotfiles.git"

has() {
  type "$1" > /dev/null 2>&1
}

usage() {
  name=`basename $0`
  cat <<EOF
Usage:
  $name [arguments] [command]
Commands:
  deploy
  initialize
Arguments:
  -f $(tput setaf 1)** warning **$(tput sgr0) Overwrite dotfiles.
  -h Print help (this message)
EOF
  exit 1
}

while getopts :f:h opt; do
  case ${opt} in
    f)
      OVERWRITE=true
      ;;
    h)
      usage
      ;;
  esac
done
shift $((OPTIND - 1))

if [ -n "${OVERWRITE}" -o ! -d ${DOT_DIRECTORY} ]; then
  echo "Downloading dotfiles..."
  rm -rf ${DOT_DIRECTORY}
  mkdir ${DOT_DIRECTORY}

  if has "git"; then
    git clone --recursive "${REMOTE_URL}" "${DOT_DIRECTORY}"
  else
    curl -fsSLo ${HOME}/dotfiles.tar.gz ${DOT_TARBALL}
    tar -zxf ${HOME}/dotfiles.tar.gz --strip-components 1 -C ${DOT_DIRECTORY}
    rm -f ${HOME}/dotfiles.tar.gz
  fi

  echo "$(tput setaf 2)Download dotfiles complete!.$(tput sgr0)"
fi

FILES_TO_SYMLINK=(

  '.bash_profile'
  '.bashrc'
  '.gitconfig'
  'etc'

)

link_files() {
  cd ${DOT_DIRECTORY}
  for f in ${FILES_TO_SYMLINK[@]}; do
    ln -snfv ${DOT_DIRECTORY}/${f} ${HOME}/${f}
  done
  echo "$(tput setaf 2)Deploy dotfiles complete!.$(tput sgr0)"
}

# initialize() {
#   bash $(DOT_DIRECTORY)/etc/init/init.sh
# }

link_files

command=$1
[ $# -gt 0 ] && shift

case $command in
  init*)
    # initialize
    ;;
  *)
    ;;
esac

exit 0
